export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const EVENTS_SCREEN = 'EVENTS_SCREEN';
export const INTRO_SCREEN = 'INTRO_SCREEN';
export const GALLERY_MODAL_SCREEN = 'GALLERY_MODAL_SCREEN';
export const LOCATION_GALLERY_SCREEN = 'LOCATION_GALLERY_SCREEN';
export const LOCATION_SCREEN = 'LOCATION_SCREEN';
export const LOCATIONS_SCREEN = 'LOCATIONS_SCREEN';
export const PERSONAL_INFO = 'PERSONAL_INFO';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const SAVED_SCREEN = 'SAVED_SCREEN';
export const TEMPLATE_SCREEN = 'TEMPLATE_SCREEN';
export const UI_KIT_DEMO_SCREEN = 'UI_KIT_DEMO_SCREEN';
export const USER_SETTINGS_SCREEN = 'USER_SETTINGS_SCREEN';
export const WORK_PLACES_SCREEN = 'WORK_PLACES_SCREEN';
export const WORK_PLACE_SCREEN = 'WORK_PLACE_SCREEN';
export const WORK_PLACES_FILTERS_SCREEN = 'WORK_PLACES_FILTERS_SCREEN';

export const COMMON_MODAL = 'COMMON_MODAL';
