import { SET_FILTER } from 'actions/work-places';
import {
	SINGLE_WORK_PLACE_TYPES, WORK_PLACE_STATUS,
	WORK_PLACES_CATEGORIES,
} from '../constants/work-places';
import IMAGE_ASSETS from '../assets/images';

const initialState = {
	filters: {
		capacity: 20,
		locationId: 'park',
		price: 6000,
		type: WORK_PLACES_CATEGORIES.OFFICE,
		windows: true,
	},
	data: {
		'1': {
			capacity: 8,
			id: '1',
			imageURI: IMAGE_ASSETS.TCEH_1,
			label: 'Офис A7',
			locationId: 'park',
			description: 'Комфортное помещение для проведение встреч и переговоров. Шумоизоляция позволит Вам общаться комфортно. Офис оснащен всеми необходимыми техническими средствами, возможна доукомплектация.',
			location: 'Tceh Park, Блок D',
			price: 4000,
			square: 25,
			type: WORK_PLACES_CATEGORIES.OFFICE,
			windows: true,
			status: WORK_PLACE_STATUS.FREE,
			photos: [
				IMAGE_ASSETS.OFFICE_1,
				IMAGE_ASSETS.OFFICE_2,
				IMAGE_ASSETS.OFFICE_3,
				IMAGE_ASSETS.OFFICE_4,
				IMAGE_ASSETS.OFFICE_5,
				IMAGE_ASSETS.OFFICE_6,
				IMAGE_ASSETS.OFFICE_7,
				IMAGE_ASSETS.OFFICE_8,
			],
		},
		'2':{
			id: '2',
			locationId: 'park',
			label: 'Офис A1',
			imageURI: IMAGE_ASSETS.OFFICE_PHOTO_1,
			type: WORK_PLACES_CATEGORIES.OFFICE,
			capacity: 10,
			price: 3000,
			square: 35,
			status: WORK_PLACE_STATUS.OCCUPATION_EXPIRING,
			windows: true,
			description: 'Комфортное помещение для проведение встреч и переговоров. Шумоизоляция позволит Вам общаться комфортно. Офис оснащен всеми необходимыми техническими средствами, возможна доукомплектация.',
			location: 'Tceh Park, Блок D',
			photos: [
				IMAGE_ASSETS.OFFICE_1,
				IMAGE_ASSETS.OFFICE_2,
				IMAGE_ASSETS.OFFICE_3,
				IMAGE_ASSETS.OFFICE_4,
				IMAGE_ASSETS.OFFICE_5,
				IMAGE_ASSETS.OFFICE_6,
				IMAGE_ASSETS.OFFICE_7,
				IMAGE_ASSETS.OFFICE_8,
			],
		},
		'3': {
			id: '3',
			locationId: 'park',
			label: 'Офис A2',
			status: WORK_PLACE_STATUS.OCCUPIED,
			imageURI: IMAGE_ASSETS.OFFICE_PHOTO_2,
			type: WORK_PLACES_CATEGORIES.OFFICE,
			capacity: 15,
			price: 5000,
			square: 55,
			windows: true,
			description: 'Комфортное помещение для проведение встреч и переговоров. Шумоизоляция позволит Вам общаться комфортно. Офис оснащен всеми необходимыми техническими средствами, возможна доукомплектация.',
			location: 'Tceh Park, Блок D',
			photos: [
				IMAGE_ASSETS.OFFICE_1,
				IMAGE_ASSETS.OFFICE_2,
				IMAGE_ASSETS.OFFICE_3,
				IMAGE_ASSETS.OFFICE_4,
				IMAGE_ASSETS.OFFICE_5,
				IMAGE_ASSETS.OFFICE_6,
				IMAGE_ASSETS.OFFICE_7,
				IMAGE_ASSETS.OFFICE_8,
			],
		},
		'4': {
			id: '4',
			locationId: 'park',
			label: 'Рабочее место',
			status: WORK_PLACE_STATUS.FREE,
			imageURI: IMAGE_ASSETS.OFFICE_PHOTO_3,
			type: WORK_PLACES_CATEGORIES.SINGLE_WORK_PLACE,
			subtype: SINGLE_WORK_PLACE_TYPES.SOFA,
			price: 1500,
			windows: true,
			description: 'Комфортное помещение для проведение встреч и переговоров. Шумоизоляция позволит Вам общаться комфортно. Офис оснащен всеми необходимыми техническими средствами, возможна доукомплектация.',
			location: 'Tceh Park, Блок D',
			photos: [
				IMAGE_ASSETS.OFFICE_1,
				IMAGE_ASSETS.OFFICE_2,
				IMAGE_ASSETS.OFFICE_3,
				IMAGE_ASSETS.OFFICE_4,
				IMAGE_ASSETS.OFFICE_5,
				IMAGE_ASSETS.OFFICE_6,
				IMAGE_ASSETS.OFFICE_7,
				IMAGE_ASSETS.OFFICE_8,
			],
		},
		'5': {
			id: '5',
			locationId: 'park',
			label: 'Рабочее место',
			status: WORK_PLACE_STATUS.OCCUPATION_EXPIRING,
			imageURI: IMAGE_ASSETS.OFFICE_10,
			type: WORK_PLACES_CATEGORIES.SINGLE_WORK_PLACE,
			subtype: SINGLE_WORK_PLACE_TYPES.TABLE,
			price: 2500,
			windows: true,
			description: 'Комфортное помещение для проведение встреч и переговоров. Шумоизоляция позволит Вам общаться комфортно. Офис оснащен всеми необходимыми техническими средствами, возможна доукомплектация.',
			location: 'Tceh Park, Блок D',
			photos: [
				IMAGE_ASSETS.OFFICE_1,
				IMAGE_ASSETS.OFFICE_2,
				IMAGE_ASSETS.OFFICE_3,
				IMAGE_ASSETS.OFFICE_4,
				IMAGE_ASSETS.OFFICE_5,
				IMAGE_ASSETS.OFFICE_6,
				IMAGE_ASSETS.OFFICE_7,
				IMAGE_ASSETS.OFFICE_8,
			],
		},
		'6': {
			id: '6',
			locationId: 'park',
			label: 'Рабочее место',
			status: WORK_PLACE_STATUS.OCCUPIED,
			imageURI: IMAGE_ASSETS.OFFICE_11,
			type: WORK_PLACES_CATEGORIES.SINGLE_WORK_PLACE,
			subtype: SINGLE_WORK_PLACE_TYPES.TABLE,
			price: 2000,
			windows: true,
			description: 'Комфортное помещение для проведение встреч и переговоров. Шумоизоляция позволит Вам общаться комфортно. Офис оснащен всеми необходимыми техническими средствами, возможна доукомплектация.',
			location: 'Tceh Park, Блок D',
			photos: [
				IMAGE_ASSETS.OFFICE_1,
				IMAGE_ASSETS.OFFICE_2,
				IMAGE_ASSETS.OFFICE_3,
				IMAGE_ASSETS.OFFICE_4,
				IMAGE_ASSETS.OFFICE_5,
				IMAGE_ASSETS.OFFICE_6,
				IMAGE_ASSETS.OFFICE_7,
				IMAGE_ASSETS.OFFICE_8,
			],
		},
	},
};

const registrationForm = (state = initialState, action) => {
	switch (action.type) {
		case SET_FILTER:
			return {
				...state,
				filters: {
					...state.filters,
					[action.payload.field]: action.payload.value,
				},
			};
		default:
			return state;
	}
};

export default registrationForm;
