export const BUTTONS_CONTAINER_HEIGHT = 200;

export const BUTTONS_CONTAINER_VISIBLE_BOTTOM = 0;
export const BUTTONS_CONTAINER_HIDDEN_BOTTOM = -1 * BUTTONS_CONTAINER_HEIGHT;

export const BUTTONS_CONTAINER_VISIBLE_OPACITY = 1;
export const BUTTONS_CONTAINER_HIDDEN_OPACITY = 0;
