export const ERROR_ICON_HIDDEN_TRANSLATE_X = -20;
export const ERROR_ICON_VISIBLE_OUTLINED_TRANSLATE_X = 15;
export const ERROR_ICON_VISIBLE_REGULAR_TRANSLATE_X = 0;
export const ERROR_TEXT_HIDDEN_TRANSLATE_Y = -15;
export const ERROR_TEXT_VISIBLE_TRANSLATE_Y = 0;
export const LABEL_CENTER_FONT_SIZE = 16;
export const LABEL_CENTER_TRANSLATE_Y = 25;
export const LABEL_INNER_PADDING = 5;
export const LABEL_TOP_FONT_SIZE = 12;
export const LABEL_TOP_TRANSLATE_Y = 2.5;
export const TEXT_LEFT_PADDING = 25;

export const LABEL_STATE = {
	TOP_ERROR: 'TOP_ERROR',
	TOP_INACTIVE: 'TOP_INACTIVE',
	TOP_ACTIVE: 'TOP_ACTIVE',
	CENTER: 'CENTER',
};

export const CONTAINER_STATE = {
	ERROR: 'ERROR',
	ACTIVE: 'ACTIVE',
	INACTIVE: 'INACTIVE',
};
